[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.12", features = ["tch"] }
burn-tch = "0.12"
ndarray = "0.15"
ndarray-npy = "0.8"

[features]
default = ["burn/default"]
